-- MySQL Script generated by MySQL Workbench
-- Mon May 21 12:13:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projet_bda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet_bda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_bda` DEFAULT CHARACTER SET utf8 ;
USE `projet_bda` ;

-- -----------------------------------------------------
-- Table `projet_bda`.`Lieux`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Lieux` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Lieux` (
  `localisation` VARCHAR(50) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`localisation`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Oeuvre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Oeuvre` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Oeuvre` (
  `id_oeuvre` INT NOT NULL AUTO_INCREMENT,
  `titre` TEXT NULL,
  `date` DATETIME NULL,
  `createur` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `Oeuvre_id_oeuvre` INT NOT NULL,
  PRIMARY KEY (`id_oeuvre`, `Oeuvre_id_oeuvre`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Idées`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Idées` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Idées` (
  `id_idee` INT NOT NULL,
  PRIMARY KEY (`id_idee`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Sortie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Sortie` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Sortie` (
  `id_sortie` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `titre` TEXT NULL,
  `description` TEXT NULL,
  `Idées_id_idee` INT NULL,
  `Lieux_localisation` VARCHAR(50) NULL,
  PRIMARY KEY (`id_sortie`),
  INDEX `fk_Sortie_Idées1_idx` (`Idées_id_idee` ASC),
  INDEX `fk_Sortie_Lieux1_idx` (`Lieux_localisation` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Spectacle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Spectacle` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Spectacle` (
  `id_spectacle` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `description` LONGTEXT NULL,
  `Lieux_localisation` VARCHAR(50) NOT NULL,
  `Oeuvre_id_oeuvre` INT NOT NULL,
  `Sortie_id_sortie` INT NULL,
  PRIMARY KEY (`id_spectacle`),
  INDEX `fk_Spectacle_Lieux1_idx` (`Lieux_localisation` ASC),
  INDEX `fk_Spectacle_Oeuvre1_idx` (`Oeuvre_id_oeuvre` ASC),
  INDEX `fk_Spectacle_Sortie1_idx` (`Sortie_id_sortie` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Associations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Associations` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Associations` (
  `nom` VARCHAR(50) NOT NULL,
  `lien` VARCHAR(255) NULL,
  `icone` LONGBLOB NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`nom`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Personne` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Personne` (
  `identifiant` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`identifiant`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Eleve`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Eleve` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Eleve` (
  `id_eleve` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `mdp` VARCHAR(255) NULL,
  `droits` LONGTEXT NULL,
  `Personne_identifiant` INT NOT NULL,
  PRIMARY KEY (`id_eleve`, `Personne_identifiant`),
  INDEX `fk_Eleve_Personne1_idx` (`Personne_identifiant` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Newsletter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Newsletter` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Newsletter` (
  `date` DATETIME NOT NULL,
  `doc` LONGTEXT NULL,
  PRIMARY KEY (`date`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Artiste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Artiste` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Artiste` (
  `nom_artiste` INT NOT NULL AUTO_INCREMENT,
  `Personne_identifiant` INT NOT NULL,
  PRIMARY KEY (`nom_artiste`, `Personne_identifiant`),
  INDEX `fk_Artiste_Personne1_idx` (`Personne_identifiant` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Newsletter_informe_Sortie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Newsletter_informe_Sortie` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Newsletter_informe_Sortie` (
  `Newsletter_date` DATETIME NOT NULL,
  `Sortie_id_sortie` INT NOT NULL,
  PRIMARY KEY (`Newsletter_date`, `Sortie_id_sortie`),
  INDEX `fk_Newsletter_has_Sortie_Sortie1_idx` (`Sortie_id_sortie` ASC),
  INDEX `fk_Newsletter_has_Sortie_Newsletter_idx` (`Newsletter_date` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Artiste_represente_Oeuvre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Artiste_represente_Oeuvre` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Artiste_represente_Oeuvre` (
  `Artiste_nom_artiste` INT NOT NULL,
  `Oeuvre_id_oeuvre` INT NOT NULL,
  PRIMARY KEY (`Artiste_nom_artiste`, `Oeuvre_id_oeuvre`),
  INDEX `fk_Artiste_has_Oeuvre_Oeuvre1_idx` (`Oeuvre_id_oeuvre` ASC),
  INDEX `fk_Artiste_has_Oeuvre_Artiste1_idx` (`Artiste_nom_artiste` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Artiste_participe_Oeuvre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Artiste_participe_Oeuvre` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Artiste_participe_Oeuvre` (
  `Artiste_nom_artiste` INT NOT NULL,
  `Oeuvre_id_oeuvre` INT NOT NULL,
  PRIMARY KEY (`Artiste_nom_artiste`, `Oeuvre_id_oeuvre`),
  INDEX `fk_Artiste_has_Oeuvre_Oeuvre2_idx` (`Oeuvre_id_oeuvre` ASC),
  INDEX `fk_Artiste_has_Oeuvre_Artiste2_idx` (`Artiste_nom_artiste` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Artiste_créé_Oeuvre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Artiste_créé_Oeuvre` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Artiste_créé_Oeuvre` (
  `Oeuvre_id_oeuvre` INT NOT NULL,
  `Artiste_nom_artiste` INT NOT NULL,
  PRIMARY KEY (`Oeuvre_id_oeuvre`, `Artiste_nom_artiste`),
  INDEX `fk_Oeuvre_has_Artiste_Artiste1_idx` (`Artiste_nom_artiste` ASC),
  INDEX `fk_Oeuvre_has_Artiste_Oeuvre1_idx` (`Oeuvre_id_oeuvre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Newsletter_informe_Oeuvre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Newsletter_informe_Oeuvre` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Newsletter_informe_Oeuvre` (
  `Oeuvre_id_oeuvre` INT NOT NULL,
  `Newsletter_date` DATETIME NOT NULL,
  PRIMARY KEY (`Oeuvre_id_oeuvre`, `Newsletter_date`),
  INDEX `fk_Oeuvre_has_Newsletter_Newsletter1_idx` (`Newsletter_date` ASC),
  INDEX `fk_Oeuvre_has_Newsletter_Oeuvre1_idx` (`Oeuvre_id_oeuvre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`Eleve_participe_Sortie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`Eleve_participe_Sortie` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`Eleve_participe_Sortie` (
  `Eleve_id_eleve` INT NOT NULL,
  `Sortie_id_sortie` INT NOT NULL,
  PRIMARY KEY (`Eleve_id_eleve`, `Sortie_id_sortie`),
  INDEX `fk_Eleve_has_Sortie_Sortie1_idx` (`Sortie_id_sortie` ASC),
  INDEX `fk_Eleve_has_Sortie_Eleve1_idx` (`Eleve_id_eleve` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`concert_de`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`concert_de` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`concert_de` (
  `Oeuvre_id_oeuvre` INT NOT NULL,
  `Oeuvre_Oeuvre_id_oeuvre` INT NOT NULL,
  `Oeuvre_id_oeuvre1` INT NOT NULL,
  `Oeuvre_Oeuvre_id_oeuvre1` INT NOT NULL,
  PRIMARY KEY (`Oeuvre_id_oeuvre`, `Oeuvre_Oeuvre_id_oeuvre`, `Oeuvre_id_oeuvre1`, `Oeuvre_Oeuvre_id_oeuvre1`),
  INDEX `fk_Oeuvre_has_Oeuvre_Oeuvre2_idx` (`Oeuvre_id_oeuvre1` ASC, `Oeuvre_Oeuvre_id_oeuvre1` ASC),
  INDEX `fk_Oeuvre_has_Oeuvre_Oeuvre1_idx` (`Oeuvre_id_oeuvre` ASC, `Oeuvre_Oeuvre_id_oeuvre` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `projet_bda`.`contenu_dans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_bda`.`contenu_dans` ;

CREATE TABLE IF NOT EXISTS `projet_bda`.`contenu_dans` (
  `Oeuvre_id_oeuvre` INT NOT NULL,
  `Oeuvre_Oeuvre_id_oeuvre` INT NOT NULL,
  `Oeuvre_id_oeuvre1` INT NOT NULL,
  `Oeuvre_Oeuvre_id_oeuvre1` INT NOT NULL,
  PRIMARY KEY (`Oeuvre_id_oeuvre`, `Oeuvre_Oeuvre_id_oeuvre`, `Oeuvre_id_oeuvre1`, `Oeuvre_Oeuvre_id_oeuvre1`),
  INDEX `fk_Oeuvre_has_Oeuvre_Oeuvre4_idx` (`Oeuvre_id_oeuvre1` ASC, `Oeuvre_Oeuvre_id_oeuvre1` ASC),
  INDEX `fk_Oeuvre_has_Oeuvre_Oeuvre3_idx` (`Oeuvre_id_oeuvre` ASC, `Oeuvre_Oeuvre_id_oeuvre` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
