<!DOCTYPE html>
<html>
    <head>
        <!-- UTF-8 (accents ...) -->
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />

        <!-- on s'assure que le rendu graphique et les entrées soit correctes sur mobile -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- font awesome icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- logo du titre de la page -->
        <link rel="shortcut icon" href="./res/images/favicon.ico" />

        <!-- le titre -->
        <title>ULC</title>

        <!-- css -->
        <link rel="stylesheet" type="text/css" href="./res/css/aside.css">
        <link rel="stylesheet" type="text/css" href="./res/css/discord.css">
        <link rel="stylesheet" type="text/css" href="./res/css/main.css">
        <link rel="stylesheet" type="text/css" href="./res/css/navbar.css">
        <link rel="stylesheet" type="text/css" href="./res/css/notification.css">
        <link rel="stylesheet" type="text/css" href="./res/css/page.css">
        <link rel="stylesheet" type="text/css" href="./res/css/sidebar.css">

        <!-- reCaptcha -->
        <script type="text/javascript" src='https://www.google.com/recaptcha/api.js'></script>

        <!-- style -->
        <script type="text/javascript" src="./res/js/animation.js"></script>
        <script type="text/javascript" src="./res/js/api.js"></script>
        <script type="text/javascript" src="./res/js/utils.js"></script>

    </head>

    <body>
