<!-- PAGE REPERTORIANT LES ECOLES -->

<div id="Liste" style="font-size: 0.8rem">
</div>
<script type="text/javascript">
function loadSchools() {
                requestAPI("/school/list/",
                	{
                		200: 	function(response) {
                		
									// la liste des écoles au format json
									var schools = JSON.parse(response).liste_ecoles;

		                        	//pour chaque école
		                        	var tab = document.createElement("table");

		                        	var line = document.createElement("tr");
		                        	var cell1 = document.createElement("th");
		                        	var cell2 = document.createElement("th");
		                        	var cell3 = document.createElement("th");
		                        	var cell4 = document.createElement("th");
		                        	var cell5 = document.createElement("th");
		                        	cell1.appendChild(document.createTextNode("Académie"));
		                        	cell2.appendChild(document.createTextNode("Nom"));
		                        	cell3.appendChild(document.createTextNode("Sigle"));
		                        	cell4.appendChild(document.createTextNode("Domaine"));
		                        	cell5.appendChild(document.createTextNode("Ville"));
		                        	line.appendChild(cell1);
									line.appendChild(cell2);
									line.appendChild(cell3);
									line.appendChild(cell4);
									line.appendChild(cell5);
									tab.appendChild(line);

									/** charge l'ecole 'i' */
		                        	function loadNextSchool(i) {
			                        	if (i >= schools.length) {
				                        	return ;
			                        	}
			                        	

										//l'école
		                        		var ecole = schools[i];
		                        		var line = document.createElement("tr");
		                        		
		                        		var cell1 = document.createElement("td");
		                        		cell1.innerHTML = ecole.academie;
		                        		
		                        		var cell2 = document.createElement("td");
		                        		cell2.innerHTML = ecole.nom;

		                        		var cell3 = document.createElement("td");
		                        		cell3.innerHTML = ecole.sigle;
										
										var cell4 = document.createElement("td");
										cell4.innerHTML = ecole.domaine;
										
										var cell5 = document.createElement("td");
										cell5.innerHTML = ecole.ville;

										line.appendChild(cell1);
										line.appendChild(cell2);
										line.appendChild(cell3);
										line.appendChild(cell4);
										line.appendChild(cell5);
										tab.appendChild(line);

										loadNextSchool(i + 1);
		                        	}
		                        	document.getElementById("Liste").appendChild(tab);
		                        	loadNextSchool(0);
                				}
                	}
                );
            }
loadSchools();
</script>