<!-- Requiet une instance de Content.php -->


        <!-- La page principal -->        
        <div class="page">

            <!-- le titre de la page -->
            <script>
                document.title = <?php echo('"ULC : ' . $this->getTitle() . '"'); ?> ;
            </script>

            <!-- le fond d'écran -->
            <!--<canvas class="page-background" id="bgCanvasID"></canvas>-->
            
